### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by ELC** [MikeS96/bayes_statististics#1]
Hi @MikeS96 

Your work in this is great!

I would really like to contribute and extend this, I am thinking probably of incorporating some symbolic calculations too with Sympy.

Would you mind adding a licenses like MIT or Apache to the project?

**Comment by MikeS96** [comment]
Hi @ELC 

Thank you for the Kudos! 

Glad to see contributions in this project :-). Just follow the normal procedure of cloning, creating awesome branch and PR. As soon as I have time I will review it and give the approval if everything seems fine.

I already added an MIT license.

Cheers!
